### ISSUE TITLE
How this compares with tkawachi/sbt-lock

### ISSUE THREAD

**Issue by jtjeferreira** [stringbean/sbt-dependency-lock#20]
Hi! 

Could you write some words in README or here how this compares with https://github.com/tkawachi/sbt-lock?

**Comment by timbertson** [comment]
It sounds like the primary purpose is that this lockfile "can be checked to see what dependencies have changed". Whereas most lock solutions by default _enforce_ their locked versions, rather than failing when the lockfile is out of sync.

**Comment by stringbean** [comment]
Apologies for the delay responding to this. Yes the main goal of this project is to better track the dependency changes. I've added a [section](https://stringbean.github.io/sbt-dependency-lock/#alternatives) to the docs comparing this to `sbt-lock`.

Forcing sbt to use what is in the lockfile is a feature that I want to add in a future version.
